cio_os: Fix 'unresolved external symbol _SHCreateDirectoryExA' on x86
Sophie Fang found that x86 Windows build fails with the following
error:

    error LNK2001: unresolved external symbol _SHCreateDirectoryExA

After investigation, it turned out that this was caused by a missing
header file in `cio_os.h`, and can be simply fixed by adding one.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>