crc32: Fix build error on macOS
macOS does not have endian.h under /usr/include.
Instead, it has at /usr/include/machine.

Otherwise, the following error occurred:

```
~/GitHub/chunkio/deps/crc32/crc32.c:20:10: fatal error:
      'endian.h' file not found
 #include <endian.h>
          ^~~~~~~~~~
1 error generated.
```

Signed-off-by: Hiroshi Hatake <cosmo0920.oucc@gmail.com>